services:

  postgres:
    image: postgres:17.6-alpine3.22
    restart: always
    # set shared memory limit when using docker compose
    shm_size: 128mb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: neukod-ale
      POSTGRES_DB: neukod

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
    pgdata:
