services:
  backend-core:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - 5049:5049
    env_file:
      - .env
    depends_on:
      - postgres
  postgres:
    image: postgres:17.6-alpine3.22
    restart: always
    # set shared memory limit when using docker compose
    shm_size: 128mb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  pgdata:
